`define H_ACTIVE_FRAME 1024
`define H_FRONT_PORCH 24
`define H_SYNC_PULSE 136
`define H_BACK_PORCH 144
`define V_ACTIVE_FRAME 768
`define V_FRONT_PORCH 3
`define V_SYNC_PULSE 6
`define V_BACK_PORCH 29
`define H_SYNC_ON (`H_ACTIVE_FRAME + `H_FRONT_PORCH - 1)
`define H_SYNC_OFF (`H_SYNC_ON + `H_SYNC_PULSE)
`define V_SYNC_ON (`V_ACTIVE_FRAME + `V_FRONT_PORCH - 1)
`define V_SYNC_OFF (`V_SYNC_ON + `V_SYNC_PULSE)
`define H_FP_BLANK_ON (`H_ACTIVE_FRAME - 1)
`define H_FP_BLANK_OFF (`H_FP_BLANK_ON + `H_FRONT_PORCH)
`define V_FP_BLANK_ON (`V_ACTIVE_FRAME - 1)
`define V_FP_BLANK_OFF (`V_FP_BLANK_ON + `V_FRONT_PORCH)
`define H_BP_BLANK_ON (`H_ACTIVE_FRAME + `H_FRONT_PORCH + `H_SYNC_PULSE - 1)
`define H_BP_BLANK_OFF (`H_BP_BLANK_ON + `H_BACK_PORCH)
`define V_BP_BLANK_ON (`V_ACTIVE_FRAME + `V_FRONT_PORCH + `V_SYNC_PULSE - 1)
`define V_BP_BLANK_OFF (`V_BP_BLANK_ON + `V_BACK_PORCH)
`define H_BOARD_SIZE 561
`define V_BOARD_SIZE 621
`define H_BOARD_ON 256
`define H_BOARD_OFF (`H_BOARD_ON + `H_BOARD_SIZE)
`define V_BOARD_ON 64
`define V_BOARD_OFF (`V_BOARD_ON + `V_BOARD_SIZE )
/** Debuging Tiles**/
`define TILE_SIZE 18
`define TILE_LINE 2
`define DOT_CENTER 9
`define TILE_CENTER 9
//HORIZONTAL
`define H_DEBUG_1_ON (`H_BOARD_ON)
`define H_DEBUG_1_OFF (`H_DEBUG_1_ON + `TILE_LINE)
`define H_DEBUG_2_ON (`H_DEBUG_1_OFF + `TILE_SIZE)
`define H_DEBUG_2_OFF (`H_DEBUG_2_ON + `TILE_LINE)
`define H_DEBUG_3_ON (`H_DEBUG_2_OFF + `TILE_SIZE)
`define H_DEBUG_3_OFF (`H_DEBUG_3_ON + `TILE_LINE)
`define H_DEBUG_4_ON (`H_DEBUG_3_OFF + `TILE_SIZE)
`define H_DEBUG_4_OFF (`H_DEBUG_4_ON + `TILE_LINE)
`define H_DEBUG_5_ON (`H_DEBUG_4_OFF + `TILE_SIZE)
`define H_DEBUG_5_OFF (`H_DEBUG_5_ON + `TILE_LINE)
`define H_DEBUG_6_ON (`H_DEBUG_5_OFF + `TILE_SIZE)
`define H_DEBUG_6_OFF (`H_DEBUG_6_ON + `TILE_LINE)
`define H_DEBUG_7_ON (`H_DEBUG_6_OFF + `TILE_SIZE)
`define H_DEBUG_7_OFF (`H_DEBUG_7_ON + `TILE_LINE)
`define H_DEBUG_8_ON (`H_DEBUG_7_OFF + `TILE_SIZE)
`define H_DEBUG_8_OFF (`H_DEBUG_8_ON + `TILE_LINE)
`define H_DEBUG_9_ON (`H_DEBUG_8_OFF + `TILE_SIZE)
`define H_DEBUG_9_OFF (`H_DEBUG_9_ON + `TILE_LINE)
`define H_DEBUG_10_ON (`H_DEBUG_9_OFF + `TILE_SIZE)
`define H_DEBUG_10_OFF (`H_DEBUG_10_ON + `TILE_LINE)
`define H_DEBUG_11_ON (`H_DEBUG_10_OFF + `TILE_SIZE)
`define H_DEBUG_11_OFF (`H_DEBUG_11_ON + `TILE_LINE)
`define H_DEBUG_12_ON (`H_DEBUG_11_OFF + `TILE_SIZE)
`define H_DEBUG_12_OFF (`H_DEBUG_12_ON + `TILE_LINE)
`define H_DEBUG_13_ON (`H_DEBUG_12_OFF + `TILE_SIZE)
`define H_DEBUG_13_OFF (`H_DEBUG_13_ON + `TILE_LINE)
`define H_DEBUG_14_ON (`H_DEBUG_13_OFF + `TILE_SIZE)
`define H_DEBUG_14_OFF (`H_DEBUG_14_ON + `TILE_LINE)
`define H_DEBUG_15_ON (`H_DEBUG_14_OFF + `TILE_SIZE)
`define H_DEBUG_15_OFF (`H_DEBUG_15_ON + `TILE_LINE)
`define H_DEBUG_16_ON (`H_DEBUG_15_OFF + `TILE_SIZE)
`define H_DEBUG_16_OFF (`H_DEBUG_16_ON + `TILE_LINE)
`define H_DEBUG_17_ON (`H_DEBUG_16_OFF + `TILE_SIZE)
`define H_DEBUG_17_OFF (`H_DEBUG_17_ON + `TILE_LINE)
`define H_DEBUG_18_ON (`H_DEBUG_17_OFF + `TILE_SIZE)
`define H_DEBUG_18_OFF (`H_DEBUG_18_ON + `TILE_LINE)
`define H_DEBUG_19_ON (`H_DEBUG_18_OFF + `TILE_SIZE)
`define H_DEBUG_19_OFF (`H_DEBUG_19_ON + `TILE_LINE)
`define H_DEBUG_20_ON (`H_DEBUG_19_OFF + `TILE_SIZE)
`define H_DEBUG_20_OFF (`H_DEBUG_20_ON + `TILE_LINE)
`define H_DEBUG_21_ON (`H_DEBUG_20_OFF + `TILE_SIZE)
`define H_DEBUG_21_OFF (`H_DEBUG_21_ON + `TILE_LINE)
`define H_DEBUG_22_ON (`H_DEBUG_21_OFF + `TILE_SIZE)
`define H_DEBUG_22_OFF (`H_DEBUG_22_ON + `TILE_LINE)
`define H_DEBUG_23_ON (`H_DEBUG_22_OFF + `TILE_SIZE)
`define H_DEBUG_23_OFF (`H_DEBUG_23_ON + `TILE_LINE)
`define H_DEBUG_24_ON (`H_DEBUG_23_OFF + `TILE_SIZE)
`define H_DEBUG_24_OFF (`H_DEBUG_24_ON + `TILE_LINE)
`define H_DEBUG_25_ON (`H_DEBUG_24_OFF + `TILE_SIZE)
`define H_DEBUG_25_OFF (`H_DEBUG_25_ON + `TILE_LINE)
`define H_DEBUG_26_ON (`H_DEBUG_25_OFF + `TILE_SIZE)
`define H_DEBUG_26_OFF (`H_DEBUG_26_ON + `TILE_LINE)
`define H_DEBUG_27_ON (`H_DEBUG_26_OFF + `TILE_SIZE)
`define H_DEBUG_27_OFF (`H_DEBUG_27_ON + `TILE_LINE)
`define H_DEBUG_28_ON (`H_DEBUG_27_OFF + `TILE_SIZE)
`define H_DEBUG_28_OFF (`H_DEBUG_28_ON + `TILE_LINE)
`define H_DEBUG_29_ON (`H_DEBUG_28_OFF + `TILE_SIZE)
`define H_DEBUG_29_OFF (`H_DEBUG_29_ON + `TILE_LINE)
`define H_DEBUG_30_ON (`H_DEBUG_29_OFF + `TILE_SIZE)
`define H_DEBUG_30_OFF (`H_DEBUG_30_ON + `TILE_LINE)
`define H_DEBUG_31_ON (`H_DEBUG_30_OFF + `TILE_SIZE)
`define H_DEBUG_31_OFF (`H_DEBUG_31_ON + `TILE_LINE)
`define H_DEBUG_32_ON (`H_DEBUG_31_OFF + `TILE_SIZE)
`define H_DEBUG_32_OFF (`H_DEBUG_32_ON + `TILE_LINE)
`define H_DEBUG_33_ON (`H_DEBUG_32_OFF + `TILE_SIZE)
`define H_DEBUG_33_OFF (`H_DEBUG_33_ON + `TILE_LINE)
`define H_DEBUG_34_ON (`H_DEBUG_33_OFF + `TILE_SIZE)
`define H_DEBUG_34_OFF (`H_DEBUG_34_ON + `TILE_LINE)
`define H_DEBUG_35_ON (`H_DEBUG_34_OFF + `TILE_SIZE)
`define H_DEBUG_35_OFF (`H_DEBUG_35_ON + `TILE_LINE)
//VERTICAL
`define V_DEBUG_1_ON (`V_BOARD_ON)
`define V_DEBUG_1_OFF (`V_DEBUG_1_ON + `TILE_LINE)
`define V_DEBUG_2_ON (`V_DEBUG_1_OFF + `TILE_SIZE)
`define V_DEBUG_2_OFF (`V_DEBUG_2_ON + `TILE_LINE)
`define V_DEBUG_3_ON (`V_DEBUG_2_OFF + `TILE_SIZE)
`define V_DEBUG_3_OFF (`V_DEBUG_3_ON + `TILE_LINE)
`define V_DEBUG_4_ON (`V_DEBUG_3_OFF + `TILE_SIZE)
`define V_DEBUG_4_OFF (`V_DEBUG_4_ON + `TILE_LINE)
`define V_DEBUG_5_ON (`V_DEBUG_4_OFF + `TILE_SIZE)
`define V_DEBUG_5_OFF (`V_DEBUG_5_ON + `TILE_LINE)
`define V_DEBUG_6_ON (`V_DEBUG_5_OFF + `TILE_SIZE)
`define V_DEBUG_6_OFF (`V_DEBUG_6_ON + `TILE_LINE)
`define V_DEBUG_7_ON (`V_DEBUG_6_OFF + `TILE_SIZE)
`define V_DEBUG_7_OFF (`V_DEBUG_7_ON + `TILE_LINE)
`define V_DEBUG_8_ON (`V_DEBUG_7_OFF + `TILE_SIZE)
`define V_DEBUG_8_OFF (`V_DEBUG_8_ON + `TILE_LINE)
`define V_DEBUG_9_ON (`V_DEBUG_8_OFF + `TILE_SIZE)
`define V_DEBUG_9_OFF (`V_DEBUG_9_ON + `TILE_LINE)
`define V_DEBUG_10_ON (`V_DEBUG_9_OFF + `TILE_SIZE)
`define V_DEBUG_10_OFF (`V_DEBUG_10_ON + `TILE_LINE)
`define V_DEBUG_11_ON (`V_DEBUG_10_OFF + `TILE_SIZE)
`define V_DEBUG_11_OFF (`V_DEBUG_11_ON + `TILE_LINE)
`define V_DEBUG_12_ON (`V_DEBUG_11_OFF + `TILE_SIZE)
`define V_DEBUG_12_OFF (`V_DEBUG_12_ON + `TILE_LINE)
`define V_DEBUG_13_ON (`V_DEBUG_12_OFF + `TILE_SIZE)
`define V_DEBUG_13_OFF (`V_DEBUG_13_ON + `TILE_LINE)
`define V_DEBUG_14_ON (`V_DEBUG_13_OFF + `TILE_SIZE)
`define V_DEBUG_14_OFF (`V_DEBUG_14_ON + `TILE_LINE)
`define V_DEBUG_15_ON (`V_DEBUG_14_OFF + `TILE_SIZE)
`define V_DEBUG_15_OFF (`V_DEBUG_15_ON + `TILE_LINE)
`define V_DEBUG_16_ON (`V_DEBUG_15_OFF + `TILE_SIZE)
`define V_DEBUG_16_OFF (`V_DEBUG_16_ON + `TILE_LINE)
`define V_DEBUG_17_ON (`V_DEBUG_16_OFF + `TILE_SIZE)
`define V_DEBUG_17_OFF (`V_DEBUG_17_ON + `TILE_LINE)
`define V_DEBUG_18_ON (`V_DEBUG_17_OFF + `TILE_SIZE)
`define V_DEBUG_18_OFF (`V_DEBUG_18_ON + `TILE_LINE)
`define V_DEBUG_19_ON (`V_DEBUG_18_OFF + `TILE_SIZE)
`define V_DEBUG_19_OFF (`V_DEBUG_19_ON + `TILE_LINE)
`define V_DEBUG_20_ON (`V_DEBUG_19_OFF + `TILE_SIZE)
`define V_DEBUG_20_OFF (`V_DEBUG_20_ON + `TILE_LINE)
`define V_DEBUG_21_ON (`V_DEBUG_20_OFF + `TILE_SIZE)
`define V_DEBUG_21_OFF (`V_DEBUG_21_ON + `TILE_LINE)
`define V_DEBUG_22_ON (`V_DEBUG_21_OFF + `TILE_SIZE)
`define V_DEBUG_22_OFF (`V_DEBUG_22_ON + `TILE_LINE)
`define V_DEBUG_23_ON (`V_DEBUG_22_OFF + `TILE_SIZE)
`define V_DEBUG_23_OFF (`V_DEBUG_23_ON + `TILE_LINE)
`define V_DEBUG_24_ON (`V_DEBUG_23_OFF + `TILE_SIZE)
`define V_DEBUG_24_OFF (`V_DEBUG_24_ON + `TILE_LINE)
`define V_DEBUG_25_ON (`V_DEBUG_24_OFF + `TILE_SIZE)
`define V_DEBUG_25_OFF (`V_DEBUG_25_ON + `TILE_LINE)
`define V_DEBUG_26_ON (`V_DEBUG_25_OFF + `TILE_SIZE)
`define V_DEBUG_26_OFF (`V_DEBUG_26_ON + `TILE_LINE)
`define V_DEBUG_27_ON (`V_DEBUG_26_OFF + `TILE_SIZE)
`define V_DEBUG_27_OFF (`V_DEBUG_27_ON + `TILE_LINE)
`define V_DEBUG_28_ON (`V_DEBUG_27_OFF + `TILE_SIZE)
`define V_DEBUG_28_OFF (`V_DEBUG_28_ON + `TILE_LINE)
`define V_DEBUG_29_ON (`V_DEBUG_28_OFF + `TILE_SIZE)
`define V_DEBUG_29_OFF (`V_DEBUG_29_ON + `TILE_LINE)
`define V_DEBUG_30_ON (`V_DEBUG_29_OFF + `TILE_SIZE)
`define V_DEBUG_30_OFF (`V_DEBUG_30_ON + `TILE_LINE)
`define V_DEBUG_31_ON (`V_DEBUG_30_OFF + `TILE_SIZE)
`define V_DEBUG_31_OFF (`V_DEBUG_31_ON + `TILE_LINE)
`define V_DEBUG_32_ON (`V_DEBUG_31_OFF + `TILE_SIZE)
`define V_DEBUG_32_OFF (`V_DEBUG_32_ON + `TILE_LINE)
`define V_DEBUG_33_ON (`V_DEBUG_32_OFF + `TILE_SIZE)
`define V_DEBUG_33_OFF (`V_DEBUG_33_ON + `TILE_LINE)
`define V_DEBUG_34_ON (`V_DEBUG_33_OFF + `TILE_SIZE)
`define V_DEBUG_34_OFF (`V_DEBUG_34_ON + `TILE_LINE)
`define V_DEBUG_35_ON (`V_DEBUG_34_OFF + `TILE_SIZE)
`define V_DEBUG_35_OFF (`V_DEBUG_35_ON + `TILE_LINE)
`define V_DEBUG_36_ON (`V_DEBUG_35_OFF + `TILE_SIZE)
`define V_DEBUG_36_OFF (`V_DEBUG_36_ON + `TILE_LINE)
`define V_DEBUG_37_ON (`V_DEBUG_36_OFF + `TILE_SIZE)
`define V_DEBUG_37_OFF (`V_DEBUG_37_ON + `TILE_LINE)
`define V_DEBUG_38_ON (`V_DEBUG_37_OFF + `TILE_SIZE)
`define V_DEBUG_38_OFF (`V_DEBUG_38_ON + `TILE_LINE)
`define V_DEBUG_39_ON (`V_DEBUG_38_OFF + `TILE_SIZE)
`define V_DEBUG_39_OFF (`V_DEBUG_39_ON + `TILE_LINE)
/** PAC-MAN **/
`define H_PACMAN_SIZE 33
`define V_PACMAN_SIZE 33
`define H_PACMAN_ON (((`H_BOARD_ON +`H_BOARD_OFF)/2) - 17 - 9)
`define H_PACMAN_OFF (`H_PACMAN_ON + `H_PACMAN_SIZE)
`define V_PACMAN_ON (((`V_BOARD_OFF *3)/4) + 5)
`define V_PACMAN_OFF (`V_PACMAN_ON + `V_PACMAN_SIZE )
`define H_PACMAN_TILE_ON (`H_PACMAN_ON + 6)
`define H_PACMAN_TILE_OFF (`H_PACMAN_TILE_ON + 21)
`define V_PACMAN_TILE_ON (`V_PACMAN_ON + 6)
`define V_PACMAN_TILE_OFF (`V_PACMAN_TILE_ON + 21)
/** GHOSTS **/
/** BLINKY **/
`define H_BLINKY_SIZE 33
`define V_BLINKY_SIZE 33
`define H_BLINKY_ON (((`H_BOARD_ON +`H_BOARD_OFF)/2) - 17 - 9)
`define H_BLINKY_OFF (`H_BLINKY_ON + `H_BLINKY_SIZE)
`define V_BLINKY_ON (((`V_BOARD_OFF * 1)/4) + 107)
`define V_BLINKY_OFF (`V_BLINKY_ON + `V_BLINKY_SIZE )
`define H_BLINKY_TILE_ON (`H_BLINKY_ON + 6)
`define H_BLINKY_TILE_OFF (`H_BLINKY_TILE_ON + 21)
`define V_BLINKY_TILE_ON (`V_BLINKY_ON + 6)
`define V_BLINKY_TILE_OFF (`V_BLINKY_TILE_ON + 21)
/** PINKY **/
`define H_PINKY_SIZE 33
`define V_PINKY_SIZE 33
`define H_PINKY_ON (((`H_BOARD_ON +`H_BOARD_OFF)/2) - 17 - 9)
`define H_PINKY_OFF (`H_PINKY_ON + `H_PINKY_SIZE)
`define V_PINKY_ON (((`V_BOARD_OFF * 1)/4) + 107)
`define V_PINKY_OFF (`V_PINKY_ON + `V_PINKY_SIZE )
`define H_PINKY_TILE_ON (`H_PINKY_ON + 6)
`define H_PINKY_TILE_OFF (`H_PINKY_TILE_ON + 21)
`define V_PINKY_TILE_ON (`V_PINKY_ON + 6)
`define V_PINKY_TILE_OFF (`V_PINKY_TILE_ON + 21)
/** INKY **/
`define H_INKY_SIZE 33
`define V_INKY_SIZE 33
`define H_INKY_ON (((`H_BOARD_ON +`H_BOARD_OFF)/2) - 17 - 9)
`define H_INKY_OFF (`H_INKY_ON + `H_INKY_SIZE)
`define V_INKY_ON (((`V_BOARD_OFF * 1)/4) + 107)
`define V_INKY_OFF (`V_INKY_ON + `V_INKY_SIZE )
`define H_INKY_TILE_ON (`H_INKY_ON + 6)
`define H_INKY_TILE_OFF (`H_INKY_TILE_ON + 21)
`define V_INKY_TILE_ON (`V_INKY_ON + 6)
`define V_INKY_TILE_OFF (`V_INKY_TILE_ON + 21)
/** CLYDE **/
`define H_CLYDE_SIZE 33
`define V_CLYDE_SIZE 33
`define H_CLYDE_ON (((`H_BOARD_ON +`H_BOARD_OFF)/2) - 17 - 9)
`define H_CLYDE_OFF (`H_CLYDE_ON + `H_CLYDE_SIZE)
`define V_CLYDE_ON (((`V_BOARD_OFF * 1)/4) + 107)
`define V_CLYDE_OFF (`V_CLYDE_ON + `V_CLYDE_SIZE )
`define H_CLYDE_TILE_ON (`H_CLYDE_ON + 6)
`define H_CLYDE_TILE_OFF (`H_CLYDE_TILE_ON + 21)
`define V_CLYDE_TILE_ON (`V_CLYDE_ON + 6)
`define V_CLYDE_TILE_OFF (`V_CLYDE_TILE_ON + 21)
/*** PACMAN STATES ***/
`define S0 5'h00
`define S1 5'h01
`define S2 5'h02
`define S3 5'h03
`define S4 5'h04
`define S5 5'h05
`define S6 5'h06
`define S7 5'h07
`define S8 5'h08
`define S9 5'h09
`define S10 5'h0a
`define S11 5'h0b
`define S12 5'h0c
`define S13 5'h0d
`define S14 5'h0e
`define S15 5'h0f
`define S16 5'h10
`define S17 5'h11
`define S18 5'h12
`define S19 5'h13
/** SCARED MODE **/
`define SCARED_MODE_MAX_TIME 15
/** SCORE **/
`define H_SCORE_SIZE 17
`define V_SCORE_SIZE 16
`define H_DIGIT_FOUR_ON (`H_BOARD_OFF - 90)
`define H_DIGIT_FOUR_OFF (`H_DIGIT_FOUR_ON + `H_SCORE_SIZE)
`define H_DIGIT_THREE_ON `H_DIGIT_FOUR_OFF
`define H_DIGIT_THREE_OFF (`H_DIGIT_THREE_ON + `H_SCORE_SIZE)
`define H_DIGIT_TWO_ON `H_DIGIT_THREE_OFF
`define H_DIGIT_TWO_OFF (`H_DIGIT_TWO_ON + `H_SCORE_SIZE)
`define H_DIGIT_ONE_ON `H_DIGIT_TWO_OFF
`define H_DIGIT_ONE_OFF (`H_DIGIT_ONE_ON + `H_SCORE_SIZE)
`define H_DIGIT_ZERO_ON `H_DIGIT_ONE_OFF
`define H_DIGIT_ZERO_OFF (`H_DIGIT_ZERO_ON + `H_SCORE_SIZE)
`define V_DIGIT_ON	(`V_BOARD_OFF)
`define V_DIGIT_OFF (`V_DIGIT_ON + `V_SCORE_SIZE)
/** LIVES **/
`define H_LIVE_SIZE 17
`define V_LIVE_SIZE 17
`define H_LIVE_THREE_ON `H_BOARD_ON
`define H_LIVE_THREE_OFF (`H_LIVE_THREE_ON + `H_LIVE_SIZE)
`define H_LIVE_TWO_ON (`H_LIVE_THREE_OFF)
`define H_LIVE_TWO_OFF (`H_LIVE_TWO_ON + `H_LIVE_SIZE)
`define H_LIVE_ONE_ON (`H_LIVE_TWO_OFF)
`define H_LIVE_ONE_OFF (`H_LIVE_ONE_ON + `H_LIVE_SIZE)
`define H_LIVE_ZERO_ON (`H_LIVE_ONE_OFF)
`define H_LIVE_ZERO_OFF (`H_LIVE_ZERO_ON + `H_LIVE_SIZE)
`define V_LIVE_ON (`V_BOARD_OFF)
`define V_LIVE_OFF (`V_LIVE_ON + `V_LIVE_SIZE)
/** BONUS **/
`define H_BONUS_SIZE 17
`define V_BONUS_SIZE 17
`define H_BONUS_ONE_ON (`H_LIVE_ZERO_OFF + 32)
`define H_BONUS_ONE_OFF (`H_BONUS_ONE_ON + `H_BONUS_SIZE)
`define H_BONUS_ZERO_ON (`H_PACMAN_ON)
`define H_BONUS_ZERO_OFF (`H_BONUS_ZERO_ON + 33)
`define V_BONUS_ONE_ON (`V_BOARD_OFF)
`define V_BONUS_ONE_OFF (`V_BONUS_ONE_ON + `V_BONUS_SIZE)
`define V_BONUS_ZERO_ON (`V_PACMAN_ON - 121)
`define V_BONUS_ZERO_OFF (`V_BONUS_ZERO_ON + 33)
`define H_READY_ON (`H_PACMAN_ON - 32)
`define H_READY_OFF (`H_READY_ON + 122)
`define V_READY_ON (`V_PACMAN_ON - 121+10)
`define V_READY_OFF (`V_READY_ON + 21)